### ISSUE TITLE
What's the benefit to use Driver<T> instead Observable<T>

### ISSUE THREAD

**Issue by GuyKahlon** [tailec/boilerplate#3]
Hey,

These days I'm looking for the best practice how to implement MVVM with RxSwift.
I found your project very interesting and useful, so thanks about that.

I've a small question for you.
What's the benefit to use Driver<T> instead Observable<T> and binding.
For example:
In your LoginViewMode you have a property:

```
let loginEnabled: Driver<Bool>

And in your LoginViewController you bind the value:

    viewModel.loginEnabled
      .driveNext { [weak self] enabled in
        self?.signinButton.enabled = enabled
      }
      .addDisposableTo(disposeBag)
```

Instead a regular Observable and Binding:
`let loginEnabled: Observable<Bool>
`
And in your LoginViewController bind the value by binding:
`viewModel.loginEnabled.bindTo(signinButton.rx_enabled).addDisposableTo(disposeBag)
`

Best,
Guy

**Comment by tailec** [comment]
Hi @GuyKahlon,

Thanks for having an interest in this project :)
`Driver` unit is 'driving' my UI.

I believe this https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Units.md#driver-unit can explain `Drivers` much better than me.

Does it answer your question?

**Comment by GuyKahlon** [comment]
@tailec Yes, I saw it before, but now, after second reading it makes sense for me, So thanks.
But one more thing, I think you should replace the code:

```
    viewModel.loginEnabled
      .driveNext { [weak self] enabled in
        self?.signinButton.enabled = enabled
      }
      .addDisposableTo(disposeBag)
```

To:

```
viewModel.loginEnabled.drive(signinButton.rx_enabled).addDisposableTo(disposeBag)
```

I'm not really sure if there any difference between the solutions, but for sure the second one is more readable and also compatible with the documentations.

Best,
Guy

**Comment by tailec** [comment]
@GuyKahlon Yeah, both solutions are exactly same and I agree with you, second one is more readable.

Changed in 1f3cb95.

Thanks for that.
