### ISSUE TITLE
Are any updates planned?

### ISSUE THREAD

**Issue by serejahh** [tailec/boilerplate#4]
I'm looking forward to see other example you described in readme

**Comment by tailec** [comment]
Hi @serejahh 
I've been busy lately. Actually, I'm working on second example

**Comment by cuongnguyenta** [comment]
Please update 
500px photo viewer app - VIPER and RxSwift
TBA - mix of MVVM and VIPER by Florent Pillet (@fpillet) and RxSwift
TODO List - MVVM and SwiftBond
Commits app - MVVM and ReactiveCocoa 👍
